import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface AuthUser {
  id: string;
  name: string;
  email: string;
  role: string;
}

const SIGNIN_URL = 'https://event.gomonetwork.com/desktop';
const VERIFY_URL = 'https://event.gomonetwork.com/api/auth/desktop/verify';

interface AuthState {
  token: string | null;
  user: AuthUser | null;
  status: 'signed-out' | 'signed-in';
  /** Nonce generated by beginSignIn(), awaiting the gomolab:// callback —
   *  matched against the deep link's own state param before trusting it. */
  pendingState: string | null;
  verifying: boolean;
  error: string | null;

  beginSignIn: () => Promise<void>;
  completeSignIn: (token: string, state: string) => boolean;
  verify: () => Promise<void>;
  signOut: () => void;
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set, get) => ({
      token: null,
      user: null,
      status: 'signed-out',
      pendingState: null,
      verifying: false,
      error: null,

      beginSignIn: async () => {
        const state = crypto.randomUUID();
        set({ pendingState: state, error: null });
        const [{ openUrl }, os] = await Promise.all([
          import('@tauri-apps/plugin-opener'),
          import('@tauri-apps/plugin-os').catch(() => null),
        ]);
        let device = '';
        if (os) {
          try {
            const host = (await os.hostname()) ?? 'Unknown host';
            device = `${host} (${os.platform()})`;
          } catch { /* not running under Tauri (e.g. dev preview in a browser) */ }
        }
        let machineId = '';
        try {
          const { invoke } = await import('@tauri-apps/api/core');
          machineId = await invoke<string>('get_machine_id');
        } catch { /* not running under Tauri */ }
        const deviceParam = device ? `&device=${encodeURIComponent(device)}` : '';
        const machineParam = machineId ? `&machineId=${encodeURIComponent(machineId)}` : '';
        await openUrl(`${SIGNIN_URL}?state=${state}${deviceParam}${machineParam}`);
      },

      completeSignIn: (token, state) => {
        if (!get().pendingState || state !== get().pendingState) {
          set({ error: 'Sign-in link is invalid or expired. Please try again.' });
          return false;
        }
        set({ token, status: 'signed-in', pendingState: null, error: null });
        get().verify();
        return true;
      },

      verify: async () => {
        const { token } = get();
        if (!token) return;
        set({ verifying: true });
        try {
          const res = await fetch(VERIFY_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ token }),
          });
          if (res.status === 401) {
            set({ token: null, user: null, status: 'signed-out', verifying: false });
            return;
          }
          if (!res.ok) { set({ verifying: false }); return; }
          const data = await res.json();
          set({ user: data.user, status: 'signed-in', verifying: false });
        } catch {
          // Network/offline failure — the 30-day token expiry is the only
          // hard backstop; don't force a sign-out just because the site is
          // unreachable right now.
          set({ verifying: false });
        }
      },

      signOut: () => set({ token: null, user: null, status: 'signed-out', pendingState: null, error: null }),
    }),
    { name: 'gomolab-auth' },
  ),
);
