import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface AuthUser {
  id: string;
  name: string;
  email: string;
  role: string;
}

const SIGNIN_URL = 'https://event.gomonetwork.com/desktop';
const VERIFY_URL = 'https://event.gomonetwork.com/api/auth/desktop/verify';

// Trimmed hex-encoded sha256 hash for constant-shape comparison — plain
// string equality on hex digests is fine here (no meaningful timing side
// channel: this only ever runs locally, comparing against a value that
// already left the server as a hash, never a secret this process holds).
async function sha256Hex(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, '0')).join('');
}

interface AuthState {
  token: string | null;
  user: AuthUser | null;
  status: 'signed-out' | 'signed-in';
  /** Nonce generated by beginSignIn(), awaiting the gomolab:// callback —
   *  matched against the deep link's own state param before trusting it. */
  pendingState: string | null;
  verifying: boolean;
  error: string | null;

  /** sha256 hash of an admin-set offline bypass PIN for this device, synced
   *  down from the last successful verify() while genuinely signed in — see
   *  DesktopSession.bypassPinHash on the website. Null means no admin has
   *  ever granted this device a bypass, so the bypass option never shows at
   *  all (see SignInGate.tsx). Persisted so it's still usable with zero
   *  connectivity, unlike everything else auth-related here. */
  bypassPinHash: string | null;
  /** True once the current app session got past the sign-in gate via PIN
   *  instead of a real sign-in — deliberately NOT persisted (unlike token),
   *  so the PIN has to be re-entered on every fresh launch rather than
   *  silently staying "unlocked" forever on a shared device. */
  offlineBypass: boolean;
  bypassError: string | null;

  beginSignIn: () => Promise<void>;
  completeSignIn: (token: string, state: string) => boolean;
  verify: () => Promise<void>;
  signOut: () => void;
  /** Checks a PIN the user typed against the cached bypassPinHash, purely
   *  locally — no network involved, so this works fully offline. Returns
   *  whether it succeeded (also reflected in offlineBypass/bypassError). */
  tryBypass: (pin: string) => Promise<boolean>;
  exitBypass: () => void;
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set, get) => ({
      token: null,
      user: null,
      status: 'signed-out',
      pendingState: null,
      verifying: false,
      error: null,
      bypassPinHash: null,
      offlineBypass: false,
      bypassError: null,

      beginSignIn: async () => {
        const state = crypto.randomUUID();
        set({ pendingState: state, error: null });
        const [{ openUrl }, os] = await Promise.all([
          import('@tauri-apps/plugin-opener'),
          import('@tauri-apps/plugin-os').catch(() => null),
        ]);
        let device = '';
        if (os) {
          try {
            const host = (await os.hostname()) ?? 'Unknown host';
            device = `${host} (${os.platform()})`;
          } catch { /* not running under Tauri (e.g. dev preview in a browser) */ }
        }
        let machineId = '';
        try {
          const { invoke } = await import('@tauri-apps/api/core');
          machineId = await invoke<string>('get_machine_id');
        } catch { /* not running under Tauri */ }
        const deviceParam = device ? `&device=${encodeURIComponent(device)}` : '';
        const machineParam = machineId ? `&machineId=${encodeURIComponent(machineId)}` : '';
        await openUrl(`${SIGNIN_URL}?state=${state}${deviceParam}${machineParam}`);
      },

      completeSignIn: (token, state) => {
        if (!get().pendingState || state !== get().pendingState) {
          set({ error: 'Sign-in link is invalid or expired. Please try again.' });
          return false;
        }
        set({ token, status: 'signed-in', pendingState: null, error: null });
        get().verify();
        return true;
      },

      verify: async () => {
        const { token } = get();
        if (!token) return;
        set({ verifying: true });
        try {
          const res = await fetch(VERIFY_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ token }),
          });
          if (res.status === 401) {
            set({ token: null, user: null, status: 'signed-out', verifying: false });
            return;
          }
          if (!res.ok) { set({ verifying: false }); return; }
          const data = await res.json();
          set({ user: data.user, status: 'signed-in', verifying: false, bypassPinHash: data.bypassPinHash ?? null });
        } catch {
          // Network/offline failure — the 30-day token expiry is the only
          // hard backstop; don't force a sign-out just because the site is
          // unreachable right now.
          set({ verifying: false });
        }
      },

      signOut: () => set({ token: null, user: null, status: 'signed-out', pendingState: null, error: null }),

      tryBypass: async (pin) => {
        const { bypassPinHash } = get();
        if (!bypassPinHash) {
          set({ bypassError: 'Offline access hasn’t been granted for this device.' });
          return false;
        }
        const hash = await sha256Hex(pin.trim());
        if (hash !== bypassPinHash) {
          set({ bypassError: 'Incorrect PIN.' });
          return false;
        }
        set({ offlineBypass: true, bypassError: null });
        return true;
      },

      exitBypass: () => set({ offlineBypass: false, bypassError: null }),
    }),
    {
      name: 'gomolab-auth',
      // offlineBypass is intentionally excluded — it must reset to false on
      // every fresh launch so the PIN has to be re-entered each time (see
      // the doc comment on the field above), unlike everything else here.
      partialize: (s) => ({ token: s.token, user: s.user, status: s.status, bypassPinHash: s.bypassPinHash }),
    },
  ),
);
