import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { useUndoStore } from './undoStore';
import { useCanvasStore } from './canvasStore';

// Upcoming fixtures — separate from matchResultsStore (completed matches with
// a final score). A scheduled match has no score; picking one from the
// scoreboard's "Load Match" picker fills in the matchup details (teams,
// logos, competition, round) so the operator doesn't retype them per game.
export interface ScheduledMatch {
  id: string;
  /** Which tournament/competition this fixture belongs to (teamDbStore-scoped). */
  tournamentId?: string;
  date: string; // "2026-08-17"
  time?: string; // "20:30"
  competition?: string;
  round?: string;
  venue?: string;
  /** Tournament category (e.g. "Men", "U21") this fixture belongs to. */
  category?: string;
  /** Draw group (e.g. "Group A") this fixture belongs to. */
  group?: string;
  /** Tiered-knockout bracket ("Cup"/"Plate"/"Bowl"/"Shield"/"Tier 5"…) this
   *  fixture belongs to — distinct from `group`, which for a knockout
   *  fixture already holds the literal stage name ("Quarterfinal") shared
   *  identically across every tier. `tier` is what actually disambiguates
   *  two same-stage matches sitting in different brackets. Undefined for
   *  every fixture except those generated by the Cup/Plate/Bowl/Shield
   *  ("Groups + Tiered Knockout") schedule format. */
  tier?: string;
  /** Manual tiebreaker for display order among fixtures sharing the same
   *  date (very common — every group/category's "Round 1" is deliberately
   *  scheduled on the same day). The Schedule tab's Move Up/Down swaps this
   *  (along with date/time) between two fixtures — without it, reordering
   *  two same-date fixtures was a no-op, since the sort below only ever
   *  looked at `date`. */
  sortIndex?: number;
  teamAName: string;
  teamAShortName?: string;
  teamALogo?: string;
  teamAColor: string;
  teamBName: string;
  teamBShortName?: string;
  teamBLogo?: string;
  teamBColor: string;
  /** 'bye' = no opponent this round (teamB is a placeholder); 'walkover' =
   *  both teams were fixtured but one forfeited — no match was actually
   *  played. Undefined means a normal fixture. */
  matchType?: 'bye' | 'walkover';
  /** Which side forfeited, for a walkover — informational + drives the badge. */
  walkoverLoser?: 'A' | 'B';
  /** User-set scoreline for a bye/walkover (no live match to derive it from),
   *  editable directly on the fixture. Carries over when sent to a scoreboard. */
  scoreA?: number;
  scoreB?: number;
  /** Set when this fixture has been sent to a scoreboard — used to grey it
   *  out and auto-advance the schedule widget's carousel past it. */
  sentAt?: number;
  /** Set when a result has been saved for this fixture (the scoreboard it was
   *  sent to had "💾 Save Result" pressed, or auto-saved on overwrite) — marks
   *  it fully completed, distinct from just having been sent. */
  completedAt?: number;
  /** Which physical venue pushed this fixture, for multi-venue cloud sync
   *  (see src/lib/cloudSync.ts) — stamped from the pushing device's own
   *  App Settings "Venue" field (appSettingsStore's `canvasVenue`), shown as
   *  a small badge so an operator can tell which venue a merged-in row came
   *  from. Undefined for fixtures that have never been pushed/pulled. */
  venueLabel?: string;
}

// sortIndex is the real ordering — an explicit, manually-arrangeable
// sequence (via the Schedule tab's Move Up/Down) independent of the
// fixture's calendar date, since many fixtures deliberately share the same
// date (every group/category's Round 1 lines up on the same day) and the
// operator wants direct control over running order regardless of that.
// Date is only a fallback tiebreaker for legacy fixtures that predate this
// field (both would tie at sortIndex 0).
export function sortMatches(a: ScheduledMatch, b: ScheduledMatch): number {
  return ((a.sortIndex ?? 0) - (b.sortIndex ?? 0)) || a.date.localeCompare(b.date);
}

interface MatchScheduleStore {
  matches: ScheduledMatch[];
  /** Fixture ids deleted locally since the last successful cloud push — read
   *  and cleared by cloudSync.ts so a deletion actually removes the record
   *  from the cloud too, instead of leaving a stale copy behind that a push
   *  only ever upserts and never removes on its own. */
  pendingDeletedIds: string[];
  addMatch: (match: Omit<ScheduledMatch, 'id'>) => string;
  updateMatch: (id: string, patch: Partial<Omit<ScheduledMatch, 'id'>>) => void;
  deleteMatch: (id: string) => void;
  markSent: (id: string) => void;
  unmarkSent: (id: string) => void;
  markCompleted: (id: string) => void;
  /** Resets sentAt/completedAt on every match, or only those in `ids` when given
   *  (e.g. the widget's currently venue-filtered view, so a scoped operator
   *  can't reset fixtures belonging to a different venue they can't even see).
   *  Also clears the score/score log/cards of any scoreboard still showing
   *  one of these fixtures, and the event log of any Timeline widget linked
   *  to it — see canvasStore's resetScoreboardStateForMatches — since a
   *  fixture being reset back to not-yet-played shouldn't leave a scoreboard
   *  or timeline still displaying stats from the reset attempt. */
  resetAllSent: (ids?: string[]) => void;
  /** Deletes every match, or only those in `ids` when given — same scoping reason. */
  clearMatches: (ids?: string[]) => void;
  restoreMatches: (matches: unknown[]) => void;
  /** Consumes (removes) the given ids from pendingDeletedIds — called by
   *  cloudSync.ts once they've actually been pushed to the cloud. */
  clearPendingDeletedIds: (ids: string[]) => void;
  /** Re-stamps every not-yet-completed fixture's Team A/B name/shortName/
   *  color/logo after the source team record's identity changes — a
   *  fixture only ever copies these fields at generation time, so without
   *  this it would keep showing whatever was true back then forever (see
   *  teamDbStore's updateTeam, and cloudSync's pull team-merge loop).
   *  Matched by the team's own PREVIOUS name + tournament (+ category, when
   *  both sides have one, so two different categories' same-named teams —
   *  e.g. a club fielding both a Boys and a Girls side — are never crossed).
   *  Completed fixtures are left alone; they're effectively historical. */
  syncTeamIdentity: (
    tournamentId: string | undefined,
    oldName: string,
    category: string | undefined,
    identity: { name?: string; shortName?: string; color?: string; logo?: string },
  ) => void;
}

export const useMatchScheduleStore = create<MatchScheduleStore>()(
  persist(
    (set, get) => ({
      matches: [],
      pendingDeletedIds: [],

      addMatch: (match) => {
        const id = crypto.randomUUID();
        set(s => {
          const nextSortIndex = s.matches.reduce((max, m) => Math.max(max, m.sortIndex ?? 0), 0) + 1;
          return { matches: [...s.matches, { ...match, id, sortIndex: match.sortIndex ?? nextSortIndex }].sort(sortMatches) };
        });
        return id;
      },

      updateMatch: (id, patch) => set(s => ({
        matches: s.matches.map(m => m.id === id ? { ...m, ...patch } : m).sort(sortMatches),
      })),

      deleteMatch: (id) => {
        const match = get().matches.find(m => m.id === id);
        set(s => ({ matches: s.matches.filter(m => m.id !== id), pendingDeletedIds: [...s.pendingDeletedIds, id] }));
        if (match) useUndoStore.getState().pushUndo(`Deleted fixture "${match.teamAName} vs ${match.teamBName}"`, () =>
          useMatchScheduleStore.setState(s => ({
            matches: [...s.matches, match].sort(sortMatches),
            pendingDeletedIds: s.pendingDeletedIds.filter(x => x !== id),
          })));
      },

      markSent: (id) => set(s => ({
        matches: s.matches.map(m => m.id === id ? { ...m, sentAt: Date.now() } : m),
      })),

      // Clears completedAt alongside sentAt (matching resetAllSent's existing
      // both-together behavior) — a fixture that's no longer "sent" shouldn't
      // still read as "completed" either. Same scoreboard/timeline cascade as
      // resetAllSent, for the same reason — this is the single-fixture form
      // of the exact same "undo, this wasn't really played" action (Undo
      // Sent / Stop Live).
      unmarkSent: (id) => {
        set(s => ({
          matches: s.matches.map(m => m.id === id ? { ...m, sentAt: undefined, completedAt: undefined } : m),
        }));
        useCanvasStore.getState().resetScoreboardStateForMatches([id]);
      },

      markCompleted: (id) => set(s => ({
        matches: s.matches.map(m => m.id === id ? { ...m, completedAt: Date.now() } : m),
      })),

      resetAllSent: (ids) => {
        const affected = ids ?? get().matches.map(m => m.id);
        set(s => ({
          matches: s.matches.map(m => affected.includes(m.id) ? { ...m, sentAt: undefined, completedAt: undefined } : m),
        }));
        useCanvasStore.getState().resetScoreboardStateForMatches(affected);
      },

      clearMatches: (ids) => {
        const removed = ids ? get().matches.filter(m => ids.includes(m.id)) : get().matches.slice();
        const removedIds = removed.map(m => m.id);
        set(s => ({
          matches: ids ? s.matches.filter(m => !ids.includes(m.id)) : [],
          pendingDeletedIds: [...s.pendingDeletedIds, ...removedIds],
        }));
        if (removed.length > 0) useUndoStore.getState().pushUndo(`Cleared ${removed.length} fixture${removed.length === 1 ? '' : 's'}`, () =>
          useMatchScheduleStore.setState(s => ({
            matches: [...s.matches, ...removed].sort(sortMatches),
            pendingDeletedIds: s.pendingDeletedIds.filter(x => !removedIds.includes(x)),
          })));
      },

      restoreMatches: (matches) => set({ matches: matches as ScheduledMatch[] }),

      clearPendingDeletedIds: (ids) => set(s => ({ pendingDeletedIds: s.pendingDeletedIds.filter(id => !ids.includes(id)) })),

      syncTeamIdentity: (tournamentId, oldName, category, identity) => set(s => ({
        matches: s.matches.map(m => {
          if (m.tournamentId !== tournamentId || m.completedAt) return m;
          if (category && m.category && m.category !== category) return m;
          if (m.teamAName !== oldName && m.teamBName !== oldName) return m;
          let next = m;
          if (m.teamAName === oldName) next = { ...next,
            teamAName: identity.name ?? next.teamAName, teamAShortName: identity.shortName,
            teamAColor: identity.color ?? next.teamAColor, teamALogo: identity.logo };
          if (m.teamBName === oldName) next = { ...next,
            teamBName: identity.name ?? next.teamBName, teamBShortName: identity.shortName,
            teamBColor: identity.color ?? next.teamBColor, teamBLogo: identity.logo };
          return next;
        }),
      })),
    }),
    {
      name: 'gomolab-match-schedule-v1',
      storage: createJSONStorage(() =>
        typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window
          ? localStorage
          : sessionStorage
      ),
      // Remote/browser clients always load the host's live data via
      // FULL_STATE — never persist locally, or a reload could show stale
      // data before (or instead of) the synced copy.
      partialize: (s) => (typeof window !== 'undefined' && !('__TAURI_INTERNALS__' in window)) ? {} : { matches: s.matches, pendingDeletedIds: s.pendingDeletedIds },
      // v1: backfills `sortIndex` for every fixture saved before that field
      // existed. Without this they'd ALL tie at sortIndex 0 — reordering any
      // one of them relative to another would silently do nothing (or look
      // like it "moved the wrong thing"), since the swap has nothing real to
      // exchange. Seeds them in their old effective order (date, then id) so
      // the pre-existing running order is preserved as the new baseline.
      version: 1,
      migrate: (persisted: any) => {
        if (!persisted?.matches) return persisted;
        const baseline = [...persisted.matches].sort((a: ScheduledMatch, b: ScheduledMatch) =>
          a.date.localeCompare(b.date) || a.id.localeCompare(b.id)
        );
        const seeded = new Map(baseline.map((m: ScheduledMatch, i: number) => [m.id, m.sortIndex ?? i]));
        return {
          ...persisted,
          matches: persisted.matches.map((m: ScheduledMatch) => ({ ...m, sortIndex: m.sortIndex ?? seeded.get(m.id) })),
        };
      },
    }
  )
);
